### ISSUE TITLE
cv_facts generates a list of list, triggering an error with cv_tasks

### ISSUE THREAD

**Issue by b-abadie** [aristanetworks/ansible-cvp#118]
Issue Type
------

 - Bug Report

Module Name
------

`cv_facts`

`arista.cvp` collection and Python libraries version

```
$ ansible --version
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/benjamin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.1 (default, Dec 21 2019, 20:57:38) [GCC 9.2.0]
```
No pip, and collection version is bleeding edge : `5a9400fc335c679a40fda1a87e10854fe58c774f` 

OS / Environment
------

CVP 2018, OS Archlinux

Summary
------

Traceback in cv_tasks when trying to execute all pending tasks

Steps to reproduce
------

```yaml
    - name: Refresh CVP facts
      local_action:
        module: arista.cvp.cv_facts
        facts:
          - tasks
      
    - name: Execute all pending CVP tasks
      local_action:
        module: arista.cvp.cv_task
        tasks: "{{ tasks }}"
        wait: 500
```

Expected results
------

Tasks running

Actual results
------

```
Traceback (most recent call last):
  File "/home/benjamin/.ansible/tmp/ansible-local-14725574msxeqb/ansible-tmp-1579195309.4717672-168986381003406/AnsiballZ_cv_task.py", line 102, in <module>
    _ansiballz_main()
  File "/home/benjamin/.ansible/tmp/ansible-local-14725574msxeqb/ansible-tmp-1579195309.4717672-168986381003406/AnsiballZ_cv_task.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/benjamin/.ansible/tmp/ansible-local-14725574msxeqb/ansible-tmp-1579195309.4717672-168986381003406/AnsiballZ_cv_task.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arista.cvp.plugins.modules.cv_task', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_arista.cvp.cv_task_payload_5txsv258/ansible_arista.cvp.cv_task_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_task.py", line 223, in <module>
  File "/tmp/ansible_arista.cvp.cv_task_payload_5txsv258/ansible_arista.cvp.cv_task_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_task.py", line 214, in main
  File "/tmp/ansible_arista.cvp.cv_task_payload_5txsv258/ansible_arista.cvp.cv_task_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_task.py", line 170, in task_action
  File "/tmp/ansible_arista.cvp.cv_task_payload_5txsv258/ansible_arista.cvp.cv_task_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_task.py", line 170, in <listcomp>
  File "/tmp/ansible_arista.cvp.cv_task_payload_5txsv258/ansible_arista.cvp.cv_task_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_task.py", line 119, in get_state
AttributeError: 'list' object has no attribute 'get'
```

After some inspection, it appears that the result of cv_facts holds a list of list of tasks, instead of  a list of tasks : 
```
ok: [hostname] => {
    "ansible_facts": {
        "cvp_info": {
            "appVersion": "Foster_Build_03",
            "version": "2018.2.5"
        },
        "tasks": [
            []
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "facts": [
                "tasks"
            ],
            "gather_subset": [
                "default"
            ]
        }
    }
}
``` 
The list is empty here (no pending task on CVP), but when called with `gather_subset: [tasks_all]`, the inner list is not empty : 
```
[[{'workOrderId': '70', <...SNIP, LOTS OF CONTENT...> , 'newParentContainerId': 'container_169_2785817860923'}]]
```

I see where is the issue, PR incoming.

**Comment by titom73** [comment]
Merged
